title: Orre Colosseum
description: The (unofficial GitHub version of the) Orre Colosseum website and documentation
theme: just-the-docs

url: https://lemonici.github.io/orre-colosseum-docs
favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Discord Server: https://discord.gg/rqSJ48PaaX
  Pokémon Showdown Dawn: https://dawn.psim.us/
  GitHub Repo: https://github.com/Lemonici/orre-colosseum-docs
